/*
 * JEquity
 * Copyright(c) 2008-2019, Beowurks
 * Original Author: Eddie Fann
 * License: Eclipse Public License - v 2.0 (https://www.eclipse.org/org/documents/epl-2.0/EPL-2.0.html)
 *
 */
// Generated by IntelliJ
// View | Tool Windows | Persistence
// Make sure that you have a hibernate.cfg.xml file in project
//
// BY THE WAY, FinancialEntity has default values for the private fields, save for the ID.
// This way, there will be no NULL values which throw errors when saving.
// This technique is not needed for the Warehouse tables as they are not updated with POJOs.
package com.beowurks.jequity.dao.hibernate;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.sql.Date;

// The schema is set in the configuration file. This way, the schema can be specific
// to the database. For example, MySQL doesn't have a schema in the traditional sense:
// The schema is the database.
// Case-sensitive issue solution: https://forum.hibernate.org/viewtopic.php?f=1&t=972808
@Entity
@Table(name = "`Financial`", catalog = "")
public class FinancialEntity implements Serializable
{

  private static final long serialVersionUID = 1L;

  private Integer financialid;

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "FINANCIALID", unique = true, nullable = false, insertable = false, updatable = false)
  public Integer getFinancialID()
  {
    return (this.financialid);
  }

  public void setFinancialID(final Integer tnFinancialID)
  {
    this.financialid = tnFinancialID;
  }

  private Integer groupid = 0;

  @Basic
  @Column(name = "GROUPID", nullable = false, insertable = true, updatable = true)
  public Integer getGroupID()
  {
    return (this.groupid);
  }

  public void setGroupID(final Integer tnGroupID)
  {
    this.groupid = tnGroupID;
  }

  private String description = "";

  @Basic
  @Column(name = "DESCRIPTION", nullable = false, insertable = true, updatable = true, length = 255)
  public String getDescription()
  {
    return (this.description);
  }

  public void setDescription(final String tcDescription)
  {
    this.description = tcDescription.trim();
  }

  private String symbol = "";

  @Basic
  @Column(name = "SYMBOL", nullable = false, insertable = true, updatable = true, length = 10)
  public String getSymbol()
  {
    return (this.symbol);
  }

  public void setSymbol(final String tcSymbol)
  {
    this.symbol = tcSymbol.trim();
  }

  private String account = "";

  @Basic
  @Column(name = "ACCOUNT", nullable = false, insertable = true, updatable = true, length = 255)
  public String getAccount()
  {
    return (this.account);
  }

  public void setAccount(final String tcAccount)
  {
    this.account = tcAccount.trim();
  }

  private String type = "";

  @Basic
  @Column(name = "TYPE", nullable = false, insertable = true, updatable = true, length = 255)
  public String getType()
  {
    return (this.type);
  }

  public void setType(final String tcType)
  {
    this.type = tcType.trim();
  }

  private String category = "";

  @Basic
  @Column(name = "CATEGORY", nullable = false, insertable = true, updatable = true, length = 255)
  public String getCategory()
  {
    return (this.category);
  }

  public void setCategory(final String tcCategory)
  {
    this.category = tcCategory.trim();
  }

  private Double shares = 0.0;

  @Basic
  @Column(name = "SHARES", nullable = false, insertable = true, updatable = true, precision = 0)
  public Double getShares()
  {
    return (this.shares);
  }

  public void setShares(final Double tnShares)
  {
    this.shares = tnShares;
  }

  private Double price = 0.0;

  @Basic
  @Column(name = "PRICE", nullable = false, insertable = true, updatable = true, precision = 0)
  public Double getPrice()
  {
    return (this.price);
  }

  public void setPrice(final Double tnPrice)
  {
    this.price = tnPrice;
  }

  private Date valuationdate = new Date(0L);

  @Basic
  @Column(name = "VALUATIONDATE", nullable = false, insertable = true, updatable = true)
  public Date getValuationDate()
  {
    return (this.valuationdate);
  }

  public void setValuationDate(final Date tdValuationDate)
  {
    this.valuationdate = tdValuationDate;
  }

  private Boolean retirement = false;

  @Basic
  @Column(name = "RETIREMENT", nullable = false, insertable = true, updatable = true)
  public Boolean getRetirement()
  {
    return (this.retirement);
  }

  public void setRetirement(final Boolean tlRetirement)
  {
    this.retirement = tlRetirement;
  }

  private Boolean taxable1099 = false;

  @Basic
  @Column(name = "TAXABLE1099", nullable = false, insertable = true, updatable = true)
  public Boolean getTaxable1099()
  {
    return (this.taxable1099);
  }

  public void setTaxable1099(final Boolean tlTaxable1099)
  {
    this.taxable1099 = tlTaxable1099;
  }

  private String comments = "";

  @Basic
  @Column(name = "COMMENTS", nullable = false, insertable = true, updatable = true, length = 32700)
  public String getComments()
  {
    return (this.comments);
  }

  public void setComments(final String tcComments)
  {
    this.comments = tcComments.trim();
  }

  @Override
  public boolean equals(final Object toObject)
  {
    if (this == toObject)
    {
      return (true);
    }
    if (toObject == null || this.getClass() != toObject.getClass())
    {
      return (false);
    }

    final FinancialEntity that = (FinancialEntity) toObject;

    if (this.account != null ? !this.account.equals(that.account) : that.account != null)
    {
      return (false);
    }
    if (this.category != null ? !this.category.equals(that.category) : that.category != null)
    {
      return (false);
    }
    if (this.comments != null ? !this.comments.equals(that.comments) : that.comments != null)
    {
      return (false);
    }
    if (this.description != null ? !this.description.equals(that.description) : that.description != null)
    {
      return (false);
    }
    if (this.financialid != null ? !this.financialid.equals(that.financialid) : that.financialid != null)
    {
      return (false);
    }
    if (this.groupid != null ? !this.groupid.equals(that.groupid) : that.groupid != null)
    {
      return (false);
    }
    if (this.price != null ? !this.price.equals(that.price) : that.price != null)
    {
      return (false);
    }
    if (this.retirement != null ? !this.retirement.equals(that.retirement) : that.retirement != null)
    {
      return (false);
    }
    if (this.taxable1099 != null ? !this.taxable1099.equals(that.taxable1099) : that.taxable1099 != null)
    {
      return (false);
    }
    if (this.shares != null ? !this.shares.equals(that.shares) : that.shares != null)
    {
      return (false);
    }
    if (this.symbol != null ? !this.symbol.equals(that.symbol) : that.symbol != null)
    {
      return (false);
    }
    if (this.type != null ? !this.type.equals(that.type) : that.type != null)
    {
      return (false);
    }
    return this.valuationdate != null ? this.valuationdate.equals(that.valuationdate) : that.valuationdate == null;
  }

  @Override
  public int hashCode()
  {
    int lnResult = this.financialid != null ? this.financialid.hashCode() : 0;
    lnResult = 31 * lnResult + (this.groupid != null ? this.groupid.hashCode() : 0);
    lnResult = 31 * lnResult + (this.description != null ? this.description.hashCode() : 0);
    lnResult = 31 * lnResult + (this.symbol != null ? this.symbol.hashCode() : 0);
    lnResult = 31 * lnResult + (this.account != null ? this.account.hashCode() : 0);
    lnResult = 31 * lnResult + (this.type != null ? this.type.hashCode() : 0);
    lnResult = 31 * lnResult + (this.category != null ? this.category.hashCode() : 0);
    lnResult = 31 * lnResult + (this.shares != null ? this.shares.hashCode() : 0);
    lnResult = 31 * lnResult + (this.price != null ? this.price.hashCode() : 0);
    lnResult = 31 * lnResult + (this.valuationdate != null ? this.valuationdate.hashCode() : 0);
    lnResult = 31 * lnResult + (this.retirement != null ? this.retirement.hashCode() : 0);
    lnResult = 31 * lnResult + (this.taxable1099 != null ? this.taxable1099.hashCode() : 0);
    lnResult = 31 * lnResult + (this.comments != null ? this.comments.hashCode() : 0);

    return (lnResult);
  }
}
