ALTER TABLE <<schema>>"Financial"
  DROP COLUMN TAXABLE1099;

ALTER TABLE <<schema>>"Financial"
  ADD COLUMN OWNERSHIP CHAR(15) DEFAULT '' NOT NULL;

ALTER TABLE <<schema>>"Financial"
  ADD COLUMN TAXSTATUS CHAR(1) DEFAULT 'T' NOT NULL;
