ALTER TABLE <<schema>>"Symbol"
  DROP COLUMN NETASSETS;

ALTER TABLE <<schema>>"Symbol"
  DROP COLUMN YTDRETURN;

ALTER TABLE <<schema>>"Symbol"
  ADD COLUMN HISTORICALINFO VARCHAR(8192) DEFAULT '' NOT NULL;
